# Generated by Django 5.1.1 on 2024-09-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='subject',
            new_name='topic',
        ),
    ]
