# Generated by Django 5.1.1 on 2024-09-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_rename_subject_topic_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='massage',
            field=models.TextField(max_length=5000, verbose_name='Message'),
        ),
    ]
